steps:
  # Maven build
  - name: 'maven'
    entrypoint: 'mvn'
    args: ['clean', 'install']

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcpavroprocessor:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gcpavroprocessor:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'gcpavroprocessor'
      - '--image'
      - 'gcr.io/$PROJECT_ID/gcpavroprocessor:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--timeout=600' #Request timeout (300s default)

images:
  - 'gcr.io/$PROJECT_ID/gcpavroprocessor:$COMMIT_SHA'
