steps:
  #maven build
  - name: 'maven'
    entrypoint: 'mvn'
    args: ['clean', 'install', '-DskipTests']

  #create docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcpavroprocessor', '.']

  #run docker image
  - name: 'docker'
    args: ['run', 'gcr.io/$PROJECT_ID/gcpavroprocessor']
images: ['gcr.io/$PROJECT_ID/gcpavroprocessor']