steps:
  - name: 'maven'
    entrypoint: 'mvn'
    args: ['clean', 'install', '-DskipTests']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcpavroprocessor', '.']
images: ['gcr.io/$PROJECT_ID/gcpavroprocessor']